---
development:
  cloud_name: railsbugzilla
  api_key: '266796753962696'
  api_secret: vgNxzIDdaPX0M_kK5YjZcXcaSRw
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: railsbugzilla
  api_key: '266796753962696'
  api_secret: vgNxzIDdaPX0M_kK5YjZcXcaSRw
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: railsbugzilla
  api_key: '266796753962696'
  api_secret: vgNxzIDdaPX0M_kK5YjZcXcaSRw
  enhance_image_tag: true
  static_file_support: false
